-- Task 4: Warehouse Performance 

-- Q1 : Find the top 3 warehouses with the highest average processing time.
SELECT *
FROM
	WAREHOUSES
ORDER BY AVERAGE_PROCESSING_TIME_MIN DESC
LIMIT 3;



-- Q2: Calculate total vs. delayed shipments for each warehouse
SELECT
	WH.WAREHOUSE_ID, WH.WAREHOUSE_NAME, TOTAL_SHIPMENTS_WH.NUM_OF_SHIPMENTS, DELAYED_SHIPMENTS_WH.NUM_OF_DELAYED_SHIPMENTS
FROM
	WAREHOUSES WH
LEFT JOIN    
(
SELECT
	W.WAREHOUSE_ID, COUNT(ST.TRACKING_ID) NUM_OF_SHIPMENTS
FROM
	WAREHOUSES W
INNER JOIN
	ORDERS O
ON O.WAREHOUSE_ID = W.WAREHOUSE_ID    
INNER JOIN
	SHIPMENT_TRACKING ST
ON ST.ORDER_ID = O.ORDER_ID
GROUP BY WAREHOUSE_ID
) TOTAL_SHIPMENTS_WH
ON WH.WAREHOUSE_ID = TOTAL_SHIPMENTS_WH.WAREHOUSE_ID
LEFT JOIN
(
SELECT
	W.WAREHOUSE_ID, COUNT(ST.TRACKING_ID) NUM_OF_DELAYED_SHIPMENTS
FROM
	WAREHOUSES W
INNER JOIN
	ORDERS O
ON O.WAREHOUSE_ID = W.WAREHOUSE_ID    
INNER JOIN
	SHIPMENT_TRACKING ST
ON ST.ORDER_ID = O.ORDER_ID
WHERE
	ST.DELAY_REASON <> 'None'
GROUP BY WAREHOUSE_ID
ORDER BY W.WAREHOUSE_ID ASC
) DELAYED_SHIPMENTS_WH
ON
TOTAL_SHIPMENTS_WH.WAREHOUSE_ID = DELAYED_SHIPMENTS_WH.WAREHOUSE_ID
ORDER BY WH.WAREHOUSE_ID ASC;


-- Q3: Use CTEs to find bottleneck warehouses where processing time > global average
WITH CTE_WH_PROCESSING_TIME AS
(    
SELECT
	WH1.WAREHOUSE_ID, WH1.WAREHOUSE_NAME, WH1.Average_Processing_Time_Min AS AVG_PROCESSING_TIME, WH2.GLOBAL_AVERAGE
FROM
		WAREHOUSES WH1
CROSS JOIN
	(SELECT ROUND(AVG(Average_Processing_Time_Min),2) AS GLOBAL_AVERAGE FROM WAREHOUSES) WH2
)
SELECT
		*
FROM
	CTE_WH_PROCESSING_TIME
WHERE
	AVG_PROCESSING_TIME > GLOBAL_AVERAGE;

-- Q4: Rank warehouses based on on-time delivery percentage

SELECT
	WH.WAREHOUSE_ID, WH.AVG_ON_TIME_DELIVERY_PECENTAGE, RANK() OVER(ORDER BY WH.AVG_ON_TIME_DELIVERY_PECENTAGE DESC) AS RANKING
FROM
(
SELECT 
	W.WAREHOUSE_ID, ROUND(AVG(DA.ON_TIME_DELIVERY_PERCENTAGE),2) AS AVG_ON_TIME_DELIVERY_PECENTAGE
FROM
	WAREHOUSES W
INNER JOIN
	ORDERS O
ON W.WAREHOUSE_ID = O.WAREHOUSE_ID
INNER JOIN
	DELIVERYAGENTS DA
ON O.AGENT_ID = DA.AGENT_ID
GROUP BY W.WAREHOUSE_ID
ORDER BY W.WAREHOUSE_ID ASC
) WH;