
-- TASK6: Shipment Tracking Analytics

-- Q1: For each order, list the last checkpoint and time
WITH CTE_CHECKPOINT_TIME AS 
(
SELECT
	ORDER_ID, CHECKPOINT_TIME, RANK() OVER(PARTITION BY ORDER_ID ORDER BY CHECKPOINT_TIME DESC) AS CHECKPOINT_TIME_RANK
FROM
	SHIPMENT_TRACKING
ORDER BY ORDER_ID
)
SELECT 
	ORDER_ID, CHECKPOINT_TIME AS LAST_CHECKPOINT_TIME
FROM
	CTE_CHECKPOINT_TIME
WHERE
	CHECKPOINT_TIME_RANK = 1
ORDER BY ORDER_ID;

-- Q2: Find the most common delay reasons (excluding None)

SELECT
	DELAY_REASON, COUNT(*) 
FROM
	SHIPMENT_TRACKING
WHERE
	DELAY_REASON <> 'None'
GROUP BY DELAY_REASON
ORDER BY COUNT(*) DESC;

-- Q3: Identify orders with >2 delayed checkpoints

SELECT
	ORDER_ID, COUNT(CHECKPOINT) AS NUM_OF_DELAYED_CHECKPOINTS
FROM
	SHIPMENT_TRACKING
WHERE
	DELAY_REASON <> 'None'
GROUP BY ORDER_ID
HAVING NUM_OF_DELAYED_CHECKPOINTS> 2
ORDER BY ORDER_ID;