-- TASK 2: Delivery Delay Analysis

-- Q1: Calculate delivery delay (in days) for each order
SELECT ORDER_ID, ROUND(SUM(DELAY_MINUTES)/1440,2) AS DELAY_IN_DAYS
FROM 
SHIPMENT_TRACKING
GROUP BY ORDER_ID;

-- Q2: Find Top 10 delayed routes based on average delay days
SELECT
	R.ROUTE_ID, R.START_LOCATION, R.END_LOCATION, TOP_10_DELAYED_ROUTES.DELAY_IN_DAYS
FROM
	ROUTES R
INNER JOIN
	(
	SELECT
		O.ROUTE_ID, ROUND(SUM(ST.DELAY_MINUTES)/1440,2) AS DELAY_IN_DAYS
	FROM
		ORDERS O
	INNER JOIN
		SHIPMENT_TRACKING ST
	ON O.ORDER_ID = ST.ORDER_ID
	GROUP BY O.ROUTE_ID
	ORDER BY DELAY_IN_DAYS DESC
	LIMIT 10) TOP_10_DELAYED_ROUTES
ON R.ROUTE_ID = TOP_10_DELAYED_ROUTES.ROUTE_ID
ORDER BY TOP_10_DELAYED_ROUTES.DELAY_IN_DAYS DESC;

-- Q3: Use window functions to rank all orders by delay within each warehouse
SELECT 
	O.WAREHOUSE_ID, O.ORDER_ID, ORDER_DELAYS.DELAY_IN_DAYS, RANK() OVER(PARTITION BY O.WAREHOUSE_ID ORDER BY ORDER_DELAYS.DELAY_IN_DAYS DESC) AS RANKING
FROM
	ORDERS O
INNER JOIN    
    (
	SELECT
		O.ORDER_ID, ROUND(SUM(ST.DELAY_MINUTES)/1440,2) AS DELAY_IN_DAYS
	FROM
		SHIPMENT_TRACKING ST
	INNER JOIN
		ORDERS O
	ON ST.ORDER_ID = O.ORDER_ID
	GROUP BY O.ORDER_ID
    ) ORDER_DELAYS
  ON O.ORDER_ID = ORDER_DELAYS.ORDER_ID;  
  
  