
-- TASK7: Advanced KPI Reporting 

-- Q1: Average Delivery Delay per Region (Start_Location)

SELECT
	R.START_LOCATION, ROUND(AVG(ST.DELAY_MINUTES),2) AS AVERAGE_DELIVERY_DELAY_MINUTES
FROM
	ROUTES R
INNER JOIN
	ORDERS O
ON O.ROUTE_ID = R.ROUTE_ID
INNER JOIN    
	SHIPMENT_TRACKING ST
ON ST.ORDER_ID = O.ORDER_ID
GROUP BY R.START_LOCATION;
	   
-- Q2: On-Time Delivery % = (Total On-Time Deliveries / Total Deliveries) * 100
SELECT 
	ROUND((TOTAL_ONTIME_DELIVERIES/TOTAL_DELIVERIES),2) * 100 AS ONTIME_DELIVERY_PERCENTAGE, TOTAL_ONTIME_DELIVERIES, TOTAL_DELIVERIES
FROM
(
SELECT
	COUNT(*) TOTAL_ONTIME_DELIVERIES
FROM
	ORDERS
WHERE
	ACTUAL_DELIVERY_DATE = EXPECTED_DELIVERY_DATE
) A
CROSS JOIN
(
SELECT COUNT(*) AS TOTAL_DELIVERIES FROM ORDERS
) B;

-- Q3: Average Traffic Delay per Route
SELECT
	O.ROUTE_ID, ROUND(AVG(ST.DELAY_MINUTES), 2) AS AVERAGE_TRAFFIC_DELAY_IN_MINUTES
FROM
	ORDERS O
INNER JOIN
	SHIPMENT_TRACKING ST	
ON O.ORDER_ID = ST.ORDER_ID
WHERE
	ST.DELAY_REASON = 'Traffic'
GROUP BY O.ROUTE_ID
ORDER BY O.ROUTE_ID;

