CREATE DATABASE FLIPKART;

USE FLIPKART;


SELECT * FROM ORDERS;
SELECT * FROM ROUTES;
SELECT * FROM WAREHOUSES;
SELECT * FROM DELIVERYAGENTS;
SELECT * FROM SHIPMENT_TRACKING;

-- TASK 1: Data Cleaning & Preparation

-- Q1: Identify and delete duplicate Order_ID records
SELECT ORDER_ID
FROM ORDERS
GROUP BY ORDER_ID
HAVING COUNT(*) >1;
-- There are no duplicate Order Ids in Order table.

-- Q2: Replace null Traffic_Delay_Min with the average delay for that route
SELECT
* FROM
ROUTES
WHERE
TRAFFIC_DELAY_MIN IS NULL;

-- Using a Temporary Table as a Workaround
CREATE TEMPORARY TABLE TEMP_AVG_TRAFFIC_DELAY AS
SELECT AVG(TRAFFIC_DELAY_MIN) AS AVG_TRAFFIC_DELAY_MIN
FROM ROUTES;

-- Update NULL values if any with the average value of TRAFFIC_DELAY_MIN
UPDATE ROUTES
JOIN TEMP_AVG_TRAFFIC_DELAY 
SET ROUTES.TRAFFIC_DELAY_MIN = TEMP_AVG_TRAFFIC_DELAY.AVG_TRAFFIC_DELAY_MIN
WHERE 
TRAFFIC_DELAY_MIN IS NULL;


-- Q3: Convert all date columns into YYYY-MM-DD format using SQL functions
ALTER TABLE ORDERS ADD (ORDER_DT DATE);
UPDATE ORDERS SET ORDER_DT = STR_TO_DATE(ORDER_DATE , '%d-%m-%Y');
ALTER TABLE ORDERS DROP ORDER_DATE;
ALTER TABLE ORDERS RENAME COLUMN ORDER_DT TO ORDER_DATE;

ALTER TABLE ORDERS ADD (EXPECTED_DELIVERY_DT DATE);
UPDATE ORDERS SET EXPECTED_DELIVERY_DT = STR_TO_DATE(EXPECTED_DELIVERY_DATE , '%d-%m-%Y');
ALTER TABLE ORDERS DROP EXPECTED_DELIVERY_DATE;
ALTER TABLE ORDERS RENAME COLUMN EXPECTED_DELIVERY_DT TO EXPECTED_DELIVERY_DATE;

ALTER TABLE ORDERS ADD (ACTUAL_DELIVERY_DT DATE);
UPDATE ORDERS SET ACTUAL_DELIVERY_DT = STR_TO_DATE(ACTUAL_DELIVERY_DATE , '%d-%m-%Y');
ALTER TABLE ORDERS DROP ACTUAL_DELIVERY_DATE;
ALTER TABLE ORDERS RENAME COLUMN ACTUAL_DELIVERY_DT TO ACTUAL_DELIVERY_DATE;

-- Q4: Ensure that no Actual_Delivery_Date is before Order_Date (flag such records)
SELECT * FROM ORDERS
WHERE
ACTUAL_DELIVERY_DATE < ORDER_DATE;
