
-- TASK 3: Route Optimization Insights

-- Q1: For each route calculate: Average delivery time (in days)
SELECT
	ROUTE_ID, ROUND(AVG(ACTUAL_DELIVERY_DATE - ORDER_DATE), 2) AS AVERAGE_DELIVERY_IN_DAYS
FROM
	ORDERS
GROUP BY ROUTE_ID
ORDER BY ROUTE_ID;

-- Q1: Average traffic delay

SELECT
	O.ROUTE_ID, ROUND(AVG(DELAY_MINUTES)/1440, 2) AS AVERAGE_TRAFFIC_DELAY_IN_DAYS
FROM
	SHIPMENT_TRACKING ST
INNER JOIN
	ORDERS O
ON ST.ORDER_ID = O.ORDER_ID
WHERE ST.DELAY_REASON = 'Traffic'
GROUP BY O.ROUTE_ID;


-- Q1: Distance-to-time efficiency ratio: Distance_KM / Average_Travel_Time_Min

SELECT
	*, ROUND((DISTANCE_KM/ AVERAGE_TRAVEL_TIME_MIN), 2) AS EFFICIENCY_RATIO
FROM
ROUTES;

-- Q2: Identify 3 routes with the worst efficiency ratio
SELECT
	*, ROUND((DISTANCE_KM/ AVERAGE_TRAVEL_TIME_MIN), 2) AS EFFICIENCY_RATIO
FROM
ROUTES
ORDER BY EFFICIENCY_RATIO ASC
LIMIT 3;

-- Q3: Find routes with >20% delayed shipments
SELECT 
	T1.ROUTE_ID, T1.NO_OF_SHIPMENTS, T2.NO_OF_DELAYED_SHIPMENTS, ROUND((T1.NO_OF_SHIPMENTS * 0.2)) AS 20PERCENT_SHIPMENTS
FROM
(SELECT 
	O.ROUTE_ID, COUNT(ST.TRACKING_ID) AS NO_OF_SHIPMENTS
FROM 
	ORDERS O
INNER JOIN
	SHIPMENT_TRACKING ST
ON O.ORDER_ID = ST.ORDER_ID    
GROUP BY O.ROUTE_ID
ORDER BY O.ROUTE_ID ASC) T1
INNER JOIN
(SELECT 
	O.ROUTE_ID, COUNT(ST.TRACKING_ID) AS NO_OF_DELAYED_SHIPMENTS
FROM 
	ORDERS O
INNER JOIN
	SHIPMENT_TRACKING ST
ON O.ORDER_ID = ST.ORDER_ID  
WHERE DELAY_MINUTES > 0  
GROUP BY O.ROUTE_ID
ORDER BY O.ROUTE_ID ASC) T2
ON
T1.ROUTE_ID = T2.ROUTE_ID;


